### ISSUE TITLE
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))

### ISSUE THREAD

**Issue by causztic** [causztic/reol-chan#9]
```
2019-08-30T02:31:47.177324+00:00 app[worker.1]: Error: Evaluation failed: TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
2019-08-30T02:31:47.177339+00:00 app[worker.1]: at __puppeteer_evaluation_script__:4:25
2019-08-30T02:31:47.177341+00:00 app[worker.1]: at ExecutionContext._evaluateInternal (/app/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
2019-08-30T02:31:47.177342+00:00 app[worker.1]: at <anonymous>
2019-08-30T02:31:47.177344+00:00 app[worker.1]: at process._tickDomainCallback (internal/process/next_tick.js:228:7)
2019-08-30T02:31:47.177346+00:00 app[worker.1]: -- ASYNC --
2019-08-30T02:31:47.177348+00:00 app[worker.1]: at ExecutionContext.<anonymous> (/app/node_modules/puppeteer/lib/helper.js:111:15)
2019-08-30T02:31:47.177349+00:00 app[worker.1]: at DOMWorld.evaluate (/app/node_modules/puppeteer/lib/DOMWorld.js:112:20)
2019-08-30T02:31:47.177351+00:00 app[worker.1]: at <anonymous>
2019-08-30T02:31:47.177352+00:00 app[worker.1]: at process._tickDomainCallback (internal/process/next_tick.js:228:7)
2019-08-30T02:31:47.177354+00:00 app[worker.1]: -- ASYNC --
2019-08-30T02:31:47.177355+00:00 app[worker.1]: at Frame.<anonymous> (/app/node_modules/puppeteer/lib/helper.js:111:15)
2019-08-30T02:31:47.177357+00:00 app[worker.1]: at Page.evaluate (/app/node_modules/puppeteer/lib/Page.js:827:43)
2019-08-30T02:31:47.177358+00:00 app[worker.1]: at Page.<anonymous> (/app/node_modules/puppeteer/lib/helper.js:112:23)
2019-08-30T02:31:47.177360+00:00 app[worker.1]: at NightStalker.getPosts (/app/node_modules/night-stalker/dist/components/NightStalker.js:177:35)
2019-08-30T02:31:47.177361+00:00 app[worker.1]: at <anonymous>
2019-08-30T02:31:47.177363+00:00 app[worker.1]: at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Comment by causztic** [comment]
Issue caused by another package.
